function getRandomItem(arr) {

    // get random index value
    const randomIndex = Math.floor(Math.random() * arr.length);

    // get random item
    const item = arr[randomIndex];

    return item;
}

let jokes = [
    "<q>Ek ladka shaadi ke liye ek ladki ko dekhne gaya Ladke ne socha ki kyun na ladki ko impress kiya jaaye aur English mein baat karne ki sochi Ladka bola: Suniye aapko English chalti hai na? Ladki sharmate hue dheere se boli: Ji bilkul chalti hai Agar SODA ho saath mein ho tab toh DESI bhi chalti hai</q>",
    "<q>A girl come in class wearing new sandals A boy comments: Chappal achhi hai Girl gusse mein: Nikalun kya? Then all the boys: Tumhaari dress toh aur bhi achchi hai</q>",
    "<q>A kanjoos boy fell in LOVE with a kanjoos Girl Girl: Jab Dad so jayenge to main gali mein ek SIKKA phenk dungi tum turrant andar aa jana Lekin ladka sikka phenne ke ek ghante baad aaya aur kuch pareshaan bhi tha Girl: Itni der kyo laga di? Boy: Wo main sikka DHOOND raha tha Girl: Pagal wo tho DHAAGA BAANDH ke phenka tha tabhi waapas kheench liya tha</q>",
    "<q>Ghalib ne girlfriend ko date par bulaya wo late aayi Girl: Am I late ? Ghalib: Arz hai Falak pe chand sitaron ko neend aa rahi hai Falak pe chand sitaron ko neend aa rahi hai Dusri ka time ho gaya hai tu ab aa rahi hai</q>",
    "<q>Husband: Dubai ja raha hun Wife: Mere liye jewellery lana Husband: Paris ja raha hun Wife: Mere liye cosmetics lana Husband: London ja raha hun Wife: Perfumes leke aana Husband: Narak mein ja raha hun Wife: Bhagwan ka diya sub kuch hai bas tum apna khyal rakhna</q>",
    "<q>A boy on a date in a BMW CAR Boy Maine tumse ek baat chupai hai Girl Kya? Boy I m already married Girl Tumne toh dara diya tha maim samjhi ki yeh red colour ki BMW tumhari nahin hai</q>",
    "<q>Ek teacher kaha ki AGAR MAI BILL GATES HOTA par essay likho Saare students likhne lag gaye Teacher ne dekha ki sab likh rahe hain but apna Pappu sirf smile kar raha tha yahan vahan dekh rajah tha lekin likh nahin raha tha Teacher: Pappu tum kyu nai likh rahey? Pappu: Madam ji main apni seceretry ka intzaar kar raha hun This is attitude</q>",
    "<q>Teacher: Kaun si chidiya sabse fast urti hai ?? Student: Mam Haathi Teacher: Nalayak Tera baap kya karta hai ??<br>Student: Ji woh Al Qaida mein aatankwadi ka kaam karte hai<br>Teacher: Shabash beta Likho bacchon answer likho HAATHI</q>",
    "<q>Sister to her brother: What are you giving to Grandmaa on her birthday? Brother: A Football Sister: Is age mein? Aur vaise bhi Grandmaa kahan khelti hai? Brother: Mere birthday per jo unhone Bhagavad Gita diya tha uska kya ?</q>",
    "<q>Boss: Kahan gaye the ? Employee: Baal katwane Boss: Office hours mein? Employee: Baal badhe bhi to office hours mein hee hai Boss: Ghar mein bhi to badhte hain Employee: To poore thode hee katwaye hai</q>",
    "<q>I found a Leaflet in newspaper this morning which read: ARE YOU AN ALCOHOLIC? CALL NOW WE CAN HELP My wife insisted I make a call I Called up It was a liquor shop offer: Buy 3 Get 1 Free Mere toh khushi ke aansu nikal aaye</q>",
    "<q>Classic examples for students of different age groups: 1st to 3rd class: Hey I studied everything for exam 4th to 6th class: Hey That question was very hard so I leave only that question 7th to 10th class: Hey Read only important questions 11th class: I think 4 chapters are enough to get pass 12th class: Kal exam kaun sa hai yaar? And in college: Abey kaminon bata toh dete aaj exam hai main toh pen bhi nahi laya</q>",
    "<q>Ek aurat chappal ki dukaan pe Aurat: Bhaiya ek chappal dikhao? Dukandaar: Number kya hai? Aurat: 36 Number Dukandaar: Bhabhi Ji dimag pe zor daalo aur soch ke batao ki kya lene aayi ho aap</q>",
    "<q>Washing powder Nirma Washing powder Nirma Doodh si safedi Nirma se Aaye Rangeen kapde bhi Khil khil jaaye Sabki pasand Nirma Washing powder Nirma Kuch bhi Post karo log padhte zarur hain Woh bhi tune ke saath</q>",
    "<q>Shadi mein juta chupai ke time dulhe ki ek saali boli: Jijaji main to 1100 lungi Second saali: Jijaji 1100 se kaam nahin chalega main toh 2100 hi lungi Peeche se Santa bola: 2310 le lo usmein bluetooth aur FM bhi aata hai</q>",
    "<q>Agar tum sab ne 2-2 ande nahi diye to tum sub ko kaat dunga Agli subah sab ne 2-2 ande diye magar 1 ne 1 anda diya Malik: Tum ne 1 anda kyun diya Usne kaha abe kaminey woh toh katne ke darr se de diya warna main toh Murga hun</q>",
    "<q>Wife saw a board outside a shop Diwali Offer Ending Today: Banarsi Saree Rs 10 Only Nylon Rs 8 only Cotton Saree Rs 5 only Excited Wife to Husband : Give me Rs 500 I ll buy 50 sarees Husband: Beerbal ki maa istri ki dukan hai woh</q>",
    "<q>Judge: Kya naam hai tumhaara? Mulzim: Huzoor Ram Lal Judge: Tum ne 10 saal se apni wife ko dabaa ke daraa ke dhamka ke apne control mein rakha hai Mulzim: Judge sahab vo aisa hai ki Judge: Khamosh Main safaai nahin maang raha hun; tarika bata tarika</q>",
    "<q>Dharam Pita not real father Dharam Maa not real mother Dharam Putra not real son Dharam Bhai not real brother Dharam Behan not real sister But how this zabardast mistake happened? Dharam PATNI means REAL WIFE Pata Karo Shashtro Main Kahan Galti Huyi</q>",
    "<q>Santa English me fail ho gaya translation ki wajah se ; 1 Mein ek aam admi hun I am a mango man 2 Mujhe English aati hai English comes to me 3 Mera talluq haripur hazara se hai I belong to green pur thousanda 4 Sdak par goliya chal rahi hai Tablets are walking on the road</q>",
    "<q>A Girl to a Boy in a train: Can I sit here? Boy: It all yours Girl: Can I take some water? Boy: Ya sure my goodness Girl thodi der ke baad: Bhaiya agla station kaun sa hai? Boy: Mere baap ne mere bheje mein GPS fit nahi kar rakha hai jaldi se seat khaali kar mujhe neend aa rahi hai</q>",
    "<q>Mrs Khanna of my society messaged me: Hi I am new on whatsapp Any idea what does IDK LY TTYL mean ? I replied: I don t know Love You Talk To You Later She replied: No problem I ll ask my son Love you too Bye and Take Care And my wife read it and Saala bhalaai ka to zamana hi nahi raha</q>",
    "<q>Traffic police chalaan book nikaal ke bola: Naam bol? Ladka: Galti ho gaya Sir Police: Naam Bol Ladka: Sorry sir is baar jane do dobara nahi hoga Police: Naam kya hai Ladka: Trikulavattyy Thekkeparambli Venkateshwara Swami Police (book band karke): Theek hai agli baar gaadi dheere chalana</q>",
    "<q>Husband: I love you Wife: Babaji ka thullu Husband: I will die for you Wife: Babaji ka thullu Husband: I can t live without you Wife: Babaji ka thullu Husband: I can do anything for you Wife: Babaji ka thullu Husband: I will give you diamond ring Wife: Really??? Husband: Babaji ka thullu</q>",
    "<q>Husband: I love you Wife: Babaji ka thullu Husband: I will die for you Wife: Babaji ka thullu Husband: I can t live without you Wife: Babaji ka thullu Husband: I can do anything for you Wife: Babaji ka thullu Husband: I will give you diamond ring Wife: Really??? Husband: Babaji ka thullu</q>",
    "<q>I m the best I can prove it I can put Coffee in coffee cup Can you put world in World Cup? OK one more: I can send my address on your mobile Can you send your mobile on my address? Nahin na Ok Ok One last one I can eat Cream biscuits with Cream Can you eat Tiger biscuits with Tiger? Kaha na only I m the best</q>",
    "<q>Officer ne Santa se pucha: Ye Haath me kya hai? Santa: Sir Banduk hai Officer: Ye Banduk Nahi Tumhari Izzat hai Shaan hai Ye Tumhari MAA hai MAA Phir Officer ne dusre sipahi Banta se pucha: Ye Hath me kya hai? Banta: Sir ye Santa ki Maa hai Uski Izzat hai Uski Shaan hai aur Hamari bhi Maa jaisi hai Maa jaisi</q>",
    "<q>Facebook ki leela sab par padi bhaari hai 71 saal ki budhiya bhi yahan kunwaari hai Chacha ki bhi kismat badal jaati hai 18 saal ki chaachi yahan mil jaati hai Ladke yahan ladkiyan ban jaate hein Nakali Id se aatank machaate hein Kuchh toh itne paagal ho jaate hein Din raat Add Me - Add Me chillaate hein</q>",
    "<q>Banta: Bhai Santa Tumhari Biwi Ka Ghutne Ka Dard Theek Hua Yaa Nahi ? Santa: Haan Yaar Doctor Ko Dikhaate Hee Theek Ho Gaya Banta (Hairani se): Achchha Kaunsi Dawa Se ? Santa: Dawa Vagaira Kuchh Nahi Bas Doctor Ne Bataya Ki Ye Budhaape Kee Nishaani Hai Aur Us Din Ke Baad Phir Usne Dard Kee Shikaayat Hee Nahi Ki</q>",
    "<q>Pyaar + Kkhayal = Maa Pyaar + Dar = Papa Pyaar + Saath = Behan Pyaar + Ladai = Bhai Pyaar + Zindagi = Girlfriend Pyaar + Masti = Friends Pyaar+Khayal+Dar +Saath+Ladai+Zindagi+Masti =Wife Married life is so easy It s just like a walk in the Park but the problem is that the Park is Jurassic Park Lo karlo walk</q>",
    "<q>Pappu: Papa Aunty ka pet itna kyun foola hua hai ? Santa: I know ki tu sab Jan ta hai badmaash Pappu: Nahin papa I don t know Santa: Chal Chal jhooth mat bol Pappu: Trust me dad pease batao na please please please Pappu: Wo yaar aunty ke pet mein paani bhara hua hai Pappu: Oh Achcha Phir toh bachcha doob jayega</q>",
    "<q>A man fron UP is introducing his family: 1 Yeh hai meri biwi Google Raani Ek sawal poocho toh 10 jawab deti hai 2 Yeh hai mera beta Facebook Kumar Ghar ki baat sare colony tak pahuchata hai 3 Yeh hai meri beti Twitter Kumari Poori colony isko folow karti hai 4 Aur mein mein hun Orkut Kumar Mujhe koi puchhta hi nahi</q>",
    "<q>Ladies of 1970s: Husb: Ek cup Coffee Wife: Abhi laee ji Ladies of 1980s: Husb: Ek cup Coffee Wife: Abhi laee Ladies of 1990s: Husb: Ek cup Coffee Wife: Laa rahi hu Ladies of 2000: Husb: Ek cup Coffee Wife: Banake pee le Ladies of 2014: Husb: Ek Cup Coffee Wife: Kya kaha? Husb: Maine kaha ek cup coffee bana du kya?</q>",
    "<q>Nayi nayi friendship hui Facebook pe numbers exchange hue aur phir Girl: Hello darling Kya kar rahe ho ??? Boy: Hai Jaanu Shave kar raha hoon Girl: Jab bhi mai tum ko call karti hoon tum shave kar rahe hote ho din mein kitni baar Shave krte ho ?? Boy: 30-40 baar Girl: Tum Pagal ho kya ??? Boy: Nahi jaanu mainn Barber hun</q>",
    "<q>Ladka apni friend se: Mere paas mere dost jaisi car nahi hai; Par tumhein palkon pe baitha ke ghumaaunga Uske jaisa bada ghar nahi hai; Par tumhein dil mein rakhunga Uske jitne paise nahi hain; Par tumhein majdoori kar ke khilaunga Aur kya chahiye tumhein???? Ladki: Bas kar pagle ab rulayega kya ? Chal apne dost ka number de</q>",
    "<q>Santa Police station ja kar kehta hai: Inspector saab mujhe ek FIR likhwaani hai Inspector: Kaun ho tum kya hua aur kiske khilaaf FIR karwaani hai? Santa: Mujhe phone par jaan se marne ki dhamki mil rahi hai Inspector: Kaun de raha hai dhamkiyaan tumko aur kya bol raha hai? Santa: BSNL wale kehte hai bill nahi bhara to kaat denge</q>",
    "<q>Chintu chup ke cigarette pee raha tha tabhi us ke papa aa gaye Chintu ne ghabrahat mein jaldi se cigarette shirt ki jeb mein chupa li Papa gusse se: Kya tum cigarette pee rahe the? Chintu: Nahin toh Papa: Toh phir tumhari shirt se yeh dhuwan kyun nikal raha hai? Chintu: Papa aap ne baat hi dil jalane wali ki hai toh dhuan toh niklega hi</q>",
    "<q>Ek husband ne apni wife ko ek SMS bheja: Thanks for making my life wonderful and being a part of my life What ever I am is only because of you You are my angel thanks for coming in my life and making it worth living You re Great Uski wife ne reply bheja: Pee li hai na ? Ab chup chap ghar aa jao DARO MAT KUCHH NAHI BOLUNGI Husband: Thank you</q>",
    "<q>Santa aur uski wife Jeeto mein jhagda hua toh Jeeto ne apni maa ko phone kiya Maa mera un se jhagda ho gaya hai Main 1 month ke liye aap ke paas aa rahi hun Jeeto s mother Jhagda kis ne start kiya?????? Jeeto Unho ne Jeeto s mother: Jhagda us kambakhat ne kiya hai saza bhi ushe hi milni chahiye Tum wahi thehro main aa rahi hun 3 Month k liye</q>",
    "<q>3rd class ka bachcha apni Miss se kehta hai: Main aapko kaisa lagta hun ? Miss: Too sweet and cute Bachcha: Toh phir main apne mummi-papa ko aap ke ghar kab bhej dunu ?? Miss: Wo kyon? Bachcha: Taaki wo hamari baat aage chalayein Miss: Yeh kya bakwas hai Baccha: Tution padhane ke liye Miss aap bhi na kasam se TV dekh dekh ke kharab ho gayi hain</q>",
    "<q>Two best friends coming out of the examination hall with chips and coke in hands First friend: Yaa aaj kaun sa paper tha??? Second friend: Shayad Maths ka tha yaar but I m not sure First friend (surprisingly): Oye you read the question paper??? Second Friend: Arrey nahin yaar Mere paas kahan time tha I saw a girl sitting besides me using a calculato</q>",
    "<q>Pathan: Wo jo table pe aadmi baitha hai us se hamara dushmani hai Dost: Table pe toh 4 aadmi hain Pathan: Wo jiski muchhein hain Dost: Muchhein to sub ki hain Pathan: Wo jis ne safed kapre pehan rakhe hain Dost: Wo toh sub ke safed hain Pathan ne gusse mein pistol nikala aur 3 aadmion ko goli maar di aur bola: Wo jo reh gaya hai usko hum nahi chhorega</q>",
    "<q>Ek gaon me bijli aane waali thi Wahan ke sabhi log khush the Bijli aane ki khushi mein sab gaon waale jhum rahe the nach rahe the gaa rahe the celebrations chal rahi thi Wahin ek kutta bhi jhum-jhum ke nach raha tha enjoy kar raha tha ann bada hi khush tha Gaon ke ek admi ne kutte se puchha Are bhai tun kyo nach raha hai ? Kutta bola Bijli ayegi to khambe bhi to lagenge</q>",
    "<q>Wife calls hubby Wife: Kahan per ho kyaya kar rahe ho? Hubby: O yaar kuch mat pucho bura haal hai Office mein hoon bahut jyada busy hoon kaam hi hi kaam hai saans lene ki bhi phursat nahin hai Aur tum batao kya kar rahi ho bachche kya kar rahe hain? Wife: KFC mein tumhare peeche bachchon ke saath bethi hun aur bachche pooch rahe hain ki papa ke saath kaun nai BUA bethi hain?</q>",
    "<q>Banta ke 4 bachche the Government ne elaan kiya: Jiske 5 bachche honge usko Rs 2000/ mahina diya jayega Banta ne apni biwi se kaha: Mera 1 beta meri girl friend ke pass hai main usko bhi le ke aata hoon Banta jab vapas Ghar aya toh apney 2 bachche gayab Banta ne apni biwi se pucha: 2 bachche Kahah hain ??? Biwi: Jis-jis ke the vo le gaye Tum ne akele ne toh elaan nahi suna tha</q>",
    "<q>Banta ki biwi kaafi bimar thi aur hospital mein admit thi Doctors ne 1 week tak uska check-up kiya sab tests kiye Saari reports aane ke baad ek senior doctor ne Banta ko bulaya aur kaha: Banta ji ek baat batani hai apko Banta: Ji doctor saaba kahiye Doctor: We are sorry Banta ji apki biwi jyada se jyada 1-2 months ki mehman hai Banta: Docor saab ismein sorry waali kya baat hai? Jahan itna time nikaal diya gujar jayenge ye 1-2 mahine bhi jais-taise</q>",
    "<q>Aurton ke Ek Group se poocha gaya ki kon kon apne SHOHRON se pyar karti hain? Sab Ne Hath khare kardiye In sab ko ek-ek msg dia giya k apne apne SHOHRON ko send karen I LOVE YOU To Inke shohron ke jawab kuch youn aaye 1: Tumhari tabiyat theek hai na? 2: Ab kya ho gaya ? phir se car maar di 3: Excuse me 4: Sirf itna batao ki kitne paise chahiye? 5: Nasha to nahi kar lia? 6: Ab kya kardia tumne? main is baar maaf nahi karoonga Aur Sab Se acha jawab ye tha 7: Kaun hain aap?</q>",
    "<q>Boy went to buy a talking parrot Boy: Main kaisa lagta hoon? Parrot: Kamine lagte ho Boy: Ye parrot badtameez hai Shopkeeper ne parrot ko pani mein duboya or pucha: Phir gali dega? Parrot: Nahin Boy Parrot se: Agar mere sath ghar me ladki aye to tum kya sochoge ? Parrot: Biwi hogi Boy: Agar 2 ladkiya ayen toh? Parrot: Biwi or saali Boy: Agar 3 aye toh? Parrot: Biwi sali or dost Boy: Agar 4 aaye toh? Parrot (apne mailk se): Paani le aao bhai Maine to pehle hi bola tha kamina hai ye sala</q>",
    "<q>Ek ladki ne new laptop liya Sham ko gusse mein bhadkti hui vapis aai aur dukan wale se boli: Ye lappy bekar hai ismein purane PC ki file paste nahi ho rahi hai Shopkeepr: Not possible Ye latest laptop he aur ismein aisa ho hi nahi sakta Ap jara batayengi ke kaise kiya aap ne copy and paste ? Ladki shop keeper ko ghar le gai apne computer ko on kiya mouse se right click kar ke file copy ki fir PC se mouse nikal ke laptop me lagaya aur right click kar ke boli: Dekho paste ka option kahna hai ? Shopkeeper on the spot be-hosh</q>",
]

const Random = getRandomItem(jokes)

document.body.querySelector(".container").lastElementChild.innerHTML = Random;